#import "../index.typ": template, tufted
#import "../../_essay/bilingual.typ": zh
#show: template.with(
  title: "What Is It Like to Be a Bat?",
  author: "Thomas Nagel",
  date: "1974",
  description: "知道蝙蝠的大脑和回声定位机制，能否知道它体验世界的感觉？",
  lang: "en",
  css: ("/assets/custom.css", "/assets/essay.css"),
)


= What Is It Like to Be a Bat? / 成为一只蝙蝠是什么感觉？

#html.p(id: "en-S001")[#text("CONSCIOUSNESS is what makes the mind-body problem really intractable. Perhaps that is why current discussions of the problem give it little attention or get it obviously wrong. The recent wave of reductionist euphoria has produced several analyses of mental phenomena and mental concepts designed to explain the possibility of some variety of materialism, psychophysical identification, or reduction.¹ But the problems dealt with are those common to this type of reduction and other types, and what makes the mind-body problem unique, and unlike the water-H₂O problem or the Turing machine-IBM machine problem or the lightning-electrical discharge problem or the gene-DNA problem or the oak tree-hydrocarbon problem, is ignored.")]

#zh(id: "S001")[#text("意识使身心问题真正难以处理。也许正因如此，当下对这个问题的讨论很少注意意识，或者明显把它弄错。近来还原主义热潮提出了多种对心理现象和心理概念的分析，旨在说明某种唯物主义、心理—物理同一性或还原的可能性。¹但它们处理的，是这类还原与其他还原共有的问题；身心问题之所以独特，区别于水与H₂O的问题、图灵机与IBM机器的问题、闪电与放电的问题、基因与DNA的问题，或橡树与碳氢化合物的问题的那些方面，却被忽略了。")]

#html.p(id: "en-S002")[#text("Every reductionist has his favorite analogy from modern science. It is most unlikely that any of these unrelated examples of successful reduction will shed light on the relation of mind to brain. But philosophers share the general human weakness for explanations of what is incomprehensible in terms suited for what is familiar and well understood, though entirely different. This has led to the acceptance of implausible accounts of the mental largely because they would permit familiar kinds of reduction. I shall try to explain why the usual examples do not help us to understand the relation between mind and body—why, indeed, we have at present no conception of what an explanation of the physical nature of a mental phenomenon would be. Without consciousness the mind-body problem would be much less interesting. With consciousness it seems hopeless. The most important and characteristic feature of conscious mental phenomena is very poorly understood. Most reductionist theories do not even try to explain it. And careful examination will show that no currently available concept of reduction is applicable to it. Perhaps a new theoretical form can be devised for the purpose, but such a solution, if it exists, lies in the distant intellectual future.")]

#zh(id: "S002")[#text("每位还原主义者都有自己偏爱的现代科学类比。这些互不相关的成功还原案例，几乎不可能阐明心灵与大脑的关系。但哲学家也有人类共同的弱点：用适于那些熟悉、理解充分，却完全不同的事物的术语，解释不可理解之物。这使人们接受了一些难以置信的心理解释，主要因为它们容许熟悉类型的还原。我将尝试说明，为什么常见例子无助于理解心灵与身体的关系——事实上，为什么我们目前根本没有概念，能够说明对心理现象的物理本性作出解释会是什么样子。没有意识，身心问题会少很多趣味；有了意识，它似乎毫无希望。人们对有意识心理现象最重要、最有特色的性质，理解得极差。多数还原主义理论甚至不尝试解释它。仔细考察会表明，目前任何可用的还原概念都不适用于它。也许可以为此构建一种新的理论形式，但这样的解决办法，即使存在，也处在遥远的思想未来。")]

#html.p(id: "en-S003")[#text("Conscious experience is a widespread phenomenon. It occurs at many levels of animal life, though we cannot be sure of its presence in the simpler organisms, and it is very difficult to say in general what provides evidence of it. (Some extremists have been prepared to deny it even of mammals other than man.) No doubt it occurs in countless forms totally unimaginable to us, on other planets in other solar systems throughout the universe. But no matter how the form may vary, the fact that an organism has conscious experience at all means, basically, that there is something it is like to be that organism. There may be further implications about the form of the experience; there may even (though I doubt it) be implications about the behavior of the organism. But fundamentally an organism has conscious mental states if and only if there is something that it is like to be that organism—something it is like for the organism.")]

#zh(id: "S003")[#text("有意识的经验是一种广泛存在的现象。它出现在动物生命的许多层次上，尽管我们不能确定较简单的生物是否也有，而且通常很难说什么能够构成证据。（某些极端论者，甚至准备否认人类之外的哺乳动物拥有经验。）毫无疑问，在宇宙中其他太阳系的其他行星上，它还会以无数我们完全无法想象的形式存在。但无论形式如何不同，一个生物拥有有意识的经验，基本上就意味着：成为这个生物，有某种感觉。这可能对经验的形式有进一步含义，甚至可能对生物的行为有含义，尽管我对此怀疑。但从根本上说，一个生物具有有意识的心理状态，当且仅当成为该生物具有某种感觉——对该生物自身而言的某种感觉。")]

#html.p(id: "en-S004")[#text("We may call this the subjective character of experience. It is not captured by any of the familiar, recently devised reductive analyses of the mental, for all of them are logically compatible with its absence. It is not analyzable in terms of any explanatory system of functional states, or intentional states, since these could be ascribed to robots or automata that behaved like people though they experienced nothing.2 It is not analyzable in terms of the causal role of experiences in relation to typical human behavior—for similar reasons.³ I do not deny that conscious mental states and events cause behavior, nor that they may be given functional characterizations. I deny only that this kind of thing exhausts their analysis. Any reductionist program has to be based on an analysis of what is to be reduced. If the analysis leaves something out, the problem will be falsely posed. It is useless to base the defense of materialism on any analysis of mental phenomena that fails to deal explicitly with their subjective character. For there is no reason to suppose that a reduction which seems plausible when no attempt is made to account for consciousness can be extended to include consciousness. Without some idea, therefore, of what the subjective character of experience is, we cannot know what is required of a physicalist theory.")]

#zh(id: "S004")[#text("我们可以称之为经验的主观特征。近期那些熟悉的心理还原分析，都没有抓住它，因为它们在逻辑上都与它的缺席相容。它不能被分析为任何功能状态或意向状态的解释系统，因为这些状态也可以归于行为像人、却毫无经验的机器人或自动机。²出于类似原因，它也不能被分析为经验相对于典型人类行为所扮演的因果角色。³我并不否认，有意识的心理状态与事件会引起行为，也不否认可以对它们作功能刻画；我否认的只是，这就穷尽了对它们的分析。任何还原主义方案，都必须基于对还原对象的分析。如果分析遗漏了某些东西，问题就被错误地提出了。依靠一种没有明确处理心理现象主观特征的分析，来捍卫唯物主义，是无用的。因为没有理由认为，一个在不解释意识时显得可信的还原，也可以扩展为包含意识。没有关于经验主观特征究竟是什么的认识，我们就无法知道物理主义理论需要满足什么要求。")]

#html.p(id: "en-S005")[#text("While an account of the physical basis of mind must explain many things, this appears to be the most difficult. It is impossible to exclude the phenomenological features of experience from a reduction in the same way that one excludes the phenomenal features of an ordinary substance from a physical or chemical reduction of it—namely, by explaining them as effects on the minds of human observers.⁴ If physicalism is to be defended, the phenomenological features must themselves be given a physical account. But when we examine their subjective character it seems that such a result is impossible. The reason is that every subjective phenomenon is essentially connected with a single point of view, and it seems inevitable that an objective, physical theory will abandon that point of view.")]

#zh(id: "S005")[#text("虽然解释心灵的物理基础，必须说明很多事情，但这一点似乎最困难。我们不能像在物理或化学还原中排除普通物质的现象特征那样，把经验的现象学特征排除出去——即把它们解释为对观察者心灵造成的效果。⁴若要捍卫物理主义，现象学特征本身就必须得到物理解释。然而，考察它们的主观特征时，这样的结果似乎不可能。原因在于，每一种主观现象都在本质上与一个特定视角相连，而一个客观的物理理论，似乎不可避免地会放弃那个视角。")]

#html.p(id: "en-S006")[#text("Let me first try to state the issue somewhat more fully than by referring to the relation between the subjective and the objective, or between the pour-soi and the en-soi. This is far from easy. Facts about what it is like to be an X are very peculiar, so peculiar that some may be inclined to doubt their reality, or the significance of claims about them. To illustrate the connection between subjectivity and a point of view, and to make evident the importance of subjective features, it will help to explore the matter in relation to an example that brings out clearly the divergence between the two types of conception, subjective and objective.")]

#zh(id: "S006")[#text("让我先尝试把问题说得更充分一些，而不只是谈主观与客观、自为与自在的关系。这远非易事。关于成为某个X是什么感觉的事实，非常特殊，特殊到有些人可能怀疑它们是否真实，或相关陈述是否有意义。为了说明主观性与视角的联系，并展示主观特征的重要性，可以考察一个清楚显示主观与客观两种理解之间差异的例子。")]

#html.p(id: "en-S007")[#text("I assume we all believe that bats have experience. After all, they are mammals, and there is no more doubt that they have experience than that mice or pigeons or whales have experience. I have chosen bats instead of wasps or flounders because if one travels too far down the phylogenetic tree, people gradually shed their faith that there is experience there at all. Bats, although more closely related to us than those other species, nevertheless present a range of activity and a sensory apparatus so different from ours that the problem I want to pose is exceptionally vivid (though it certainly could be raised with other species). Even without the benefit of philosophical reflection, anyone who has spent some time in an enclosed space with an excited bat knows what it is to encounter a fundamentally alien form of life.")]

#zh(id: "S007")[#text("我假定，我们都相信蝙蝠有经验。毕竟它们是哺乳动物；与相信老鼠、鸽子或鲸有经验相比，相信蝙蝠有经验并没有更多可疑之处。我选择蝙蝠，而非黄蜂或比目鱼，是因为沿系统发育树向下走得太远，人们会逐渐不再相信那里存在经验。尽管蝙蝠与我们的亲缘关系，比那些其他物种更近，但它们的活动范围与感觉器官，又与我们差异极大，使我想提出的问题格外鲜明，虽然它当然也可以针对其他物种提出。即使没有哲学反思的帮助，任何曾在封闭空间里与一只兴奋蝙蝠相处过的人，也知道遇上一种根本异己的生命形式是什么感觉。")]

#html.p(id: "en-S008")[#text("I have said that the essence of the belief that bats have experience is that there is something that it is like to be a bat. Now we know that most bats (the microchiroptera, to be precise) perceive the external world primarily by sonar, or echolocation, detecting the reflections, from objects within range, of their own rapid, subtly modulated, high-frequency shrieks. Their brains are designed to correlate the outgoing impulses with the subsequent echoes, and the information thus acquired enables bats to make precise discriminations of distance, size, shape, motion, and texture comparable to those we make by vision. But bat sonar, though clearly a form of perception, is not similar in its operation to any sense that we possess, and there is no reason to suppose that it is subjectively like anything we can experience or imagine. This appears to create difficulties for the notion of what it is like to be a bat. We must consider whether any method will permit us to extrapolate to the inner life of the bat from our own case,5 and if not, what alternative methods there may be for understanding the notion.")]

#zh(id: "S008")[#text("我已经说过，相信蝙蝠有经验，其要点就是成为蝙蝠具有某种感觉。我们知道，多数蝙蝠，准确说是小蝙蝠亚目，主要依靠声呐，即回声定位感知外界：它们发出快速、精细调制的高频尖叫，检测范围内物体反射回来的声音。它们的大脑能够把发出的脉冲与随后回声关联起来，由此获得的信息，使它们精确辨别距离、大小、形状、运动和质地，其能力可与我们的视觉相比。但蝙蝠声呐虽然明显是一种知觉，其运作却不像我们拥有的任何感觉；也没有理由认为，它在主观上类似于我们能够体验或想象的任何东西。这似乎给“成为蝙蝠是什么感觉”这一观念带来困难。我们必须考虑，是否有某种方法允许从我们自身的情形，推演到蝙蝠的内在生活；⁵如果没有，还有什么其他方法可以理解这个观念。")]

#html.p(id: "en-S009")[#text("Our own experience provides the basic material for our imagination, whose range is therefore limited. It will not help to try to imagine that one has webbing on one's arms, which enables one to fly around at dusk and dawn catching insects in one's mouth; that one has very poor vision, and perceives the surrounding world by a system of reflected high-frequency sound signals; and that one spends the day hanging upside down by one's feet in an attic. In so far as I can imagine this (which is not very far), it tells me only what it would be like for me to behave as a bat behaves. But that is not the question. I want to know what it is like for a bat to be a bat. Yet if I try to imagine this, I am restricted to the resources of my own mind, and those resources are inadequate to the task. I cannot perform it either by imagining additions to my present experience, or by imagining segments gradually subtracted from it, or by imagining some combination of additions, subtractions, and modifications.")]

#zh(id: "S009")[#text("我们自身的经验为想象提供基本材料，因此想象的范围有限。试着想象手臂上有蹼，让自己能在黄昏与黎明飞来飞去，用嘴捕捉昆虫；视力很差，通过反射的高频声音信号系统感知周围；白天用脚倒挂在阁楼里——这样做并无帮助。在我能够想象这些的范围内，而这个范围很有限，它只告诉我：如果我像蝙蝠那样行动，对我而言会是什么感觉。但这并不是问题。我想知道的是，对蝙蝠而言，成为蝙蝠是什么感觉。然而，试图想象时，我只能依靠自己头脑的资源，而这些资源不足以完成任务。无论想象给当前经验增加些什么，逐步减去部分经验，还是把增加、减去与修改结合起来，都无法做到。")]

#html.p(id: "en-S010")[#text("To the extent that I could look and behave like a wasp or a bat without changing my fundamental structure, my experiences would not be anything like the experiences of those animals. On the other hand, it is doubtful that any meaning can be attached to the supposition that I should possess the internal neurophysiological constitution of a bat. Even if I could by gradual degrees be transformed into a bat, nothing in my present constitution enables me to imagine what the experiences of such a future stage of myself thus metamorphosed would be like. The best evidence would come from the experiences of bats, if we only knew what they were like.")]

#zh(id: "S010")[#text("在不改变我根本结构的范围内，即使外表和行为像黄蜂或蝙蝠，我的经验也不会像那些动物的经验。另一方面，假设我拥有蝙蝠内部的神经生理构造，究竟有没有意义，也值得怀疑。即使我能够逐渐变成蝙蝠，目前构造中也没有什么，使我能想象这种变形之后，未来阶段的自己会有怎样的经验。最好的证据应来自蝙蝠的经验，只要我们知道它们是什么感觉。")]

#html.p(id: "en-S011")[#text("So if extrapolation from our own case is involved in the idea of what it is like to be a bat, the extrapolation must be incompletable. We cannot form more than a schematic conception of what it is like. For example, we may ascribe general types of experience on the basis of the animal's structure and behavior. Thus we describe bat sonar as a form of three-dimensional forward perception; we believe that bats feel some versions of pain, fear, hunger, and lust, and that they have other, more familiar types of perception besides sonar. But we believe that these experiences also have in each case a specific subjective character, which it is beyond our ability to conceive. And if there is conscious life elsewhere in the universe, it is likely that some of it will not be describable even in the most general experiential terms available to us.6 (The problem is not confined to exotic cases, however, for it exists between one person and another. The subjective character of the experience of a person deaf and blind from birth is not accessible to me, for example, nor presumably is mine to him. This does not prevent us each from believing that the other's experience has such a subjective character.)")]

#zh(id: "S011")[#text("因此，如果“成为蝙蝠是什么感觉”这个观念涉及从自身情形外推，那么这种外推必定无法完成。我们只能形成一种概略的理解。例如，我们可以根据动物的结构和行为，归予它一般类型的经验。于是，把蝙蝠声呐描述为三维的前向知觉；相信蝙蝠会感觉某种疼痛、恐惧、饥饿和欲望，除声呐外，还有其他更熟悉的知觉类型。但我们也相信，每一种经验都具有某种具体的主观特征，而我们没有能力构想它。如果宇宙其他地方存在有意识的生命，其中某些生命，很可能连用我们最一般的经验术语都无法描述。⁶不过，问题并不限于奇异案例，因为它也存在于人与人之间。例如，一个生来既聋又盲的人的经验，其主观特征对我不可通达；想必我的主观特征对他也如此。这并不妨碍我们各自相信，对方的经验具有这样的主观特征。")]

#html.p(id: "en-S012")[#text("If anyone is inclined to deny that we can believe in the existence of facts like this whose exact nature we cannot possibly conceive, he should reflect that in contemplating the bats we are in much the same position that intelligent bats or Martians7 would occupy if they tried to form a conception of what it was like to be us. The structure of their own minds might make it impossible for them to succeed, but we know they would be wrong to conclude that there is not anything precise that it is like to be us: that only certain general types of mental state could be ascribed to us (perhaps perception and appetite would be concepts common to us both; perhaps not). We know they would be wrong to draw such a skeptical conclusion because we know what it is like to be us. And we know that while it includes an enormous amount of variation and complexity, and while we do not possess the vocabulary to describe it adequately, its subjective character is highly specific, and in some respects describable in terms that can be understood only by creatures like us. The fact that we cannot expect ever to accommodate in our language a detailed description of Martian or bat phenomenology should not lead us to dismiss as meaningless the claim that bats and Martians have experiences fully comparable in richness of detail to our own. It would be fine if someone were to develop concepts and a theory that enabled us to think about those things; but such an understanding may be permanently denied to us by the limits of our nature. And to deny the reality or logical significance of what we can never describe or understand is the crudest form of cognitive dissonance.")]

#zh(id: "S012")[#text("如果有人倾向于否认：我们能够相信这种事实存在，尽管根本不可能构想其准确性质，那么他应当反思，面对蝙蝠时，我们所处的位置，基本上就像有智慧的蝙蝠或火星人⁷试图理解成为我们是什么感觉时的位置。它们的心灵结构也许使其不可能成功，但我们知道，它们若据此认定成为我们没有任何确定的感觉，而只能归予我们某些一般类型的心理状态，就会是错的；也许知觉和欲求是双方共有的概念，也许不是。我们知道，这种怀疑性结论是错的，因为我们知道成为自己是什么感觉。我们还知道，尽管其中有极多变化和复杂性，尽管我们缺乏充分描述它的词汇，它的主观特征仍高度具体，并且某些方面只能用我们这类生物才理解的术语描述。我们不能期望自己的语言容纳对火星人或蝙蝠现象学的详细描述，这不应使我们认为，蝙蝠和火星人的经验在细节丰富程度上完全可与我们的经验相比这一说法毫无意义。若有人发展出概念与理论，使我们能思考这些事物，那当然很好；但我们本性的限制，也许会永久阻止这种理解。否认我们永远无法描述或理解的事物具有现实性或逻辑意义，是最粗糙的认知失调。")]

#html.p(id: "en-S013")[#text("This brings us to the edge of a topic that requires much more discussion than I can give it here: namely, the relation between facts on the one hand and conceptual schemes or systems of representation on the other. My realism about the subjective domain in all its forms implies a belief in the existence of facts beyond the reach of human concepts. Certainly it is possible for a human being to believe that there are facts which humans never will possess the requisite concepts to represent or comprehend. Indeed, it would be foolish to doubt this, given the finiteness of humanity's expectations. After all, there would have been transfinite numbers even if everyone had been wiped out by the Black Death before Cantor discovered them. But one might also believe that there are facts which could not ever be represented or comprehended by human beings, even if the species lasted forever-simply because our structure does not permit us to operate with concepts of the requisite type. This impossibility might even be observed by other beings, but it is not clear that the existence of such beings, or the possibility of their existence, is a precondition of the significance of the hypothesis that there are humanly inaccessible facts. (After all, the nature of beings with access to humanly inaccessible facts is presumably itself a humanly inaccessible fact.) Reflection on what it is like to be a bat seems to lead us, therefore, to the conclusion that there are facts that do not consist in the truth of propositions expressible in a human language. We can be compelled to recognize the existence of such facts without being able to state or comprehend them.")]

#zh(id: "S013")[#text("这把我们带到一个话题的边缘：一边是事实，另一边是概念框架或表征系统，两者有什么关系？它所需的讨论远超这里能提供的篇幅。我对各种形式的主观领域持实在论，意味着相信存在超出人类概念范围的事实。人当然可以相信，有些事实，人类永远不会拥有表征或理解它们所需的概念。考虑到人类前景的有限性，怀疑这一点反而愚蠢。毕竟，即使康托尔发现超限数之前，所有人就都死于黑死病，超限数也依然存在。但人也可能相信，有些事实即便人类永远存在，也永远不能表征或理解，只因为我们的结构不允许操作所需类型的概念。其他生物甚至可能观察到这种不可能性，但不清楚它们的存在，或存在的可能性，是否是“存在人类无法通达的事实”这一假说有意义的前提。毕竟，能通达人类无法通达事实的生物，其本性想必也属于人类无法通达的事实。因此，思考成为蝙蝠是什么感觉，似乎引导我们得出结论：有些事实，并不等同于人类语言可表达的命题为真。我们可能被迫承认这些事实存在，却不能陈述或理解它们。")]

#html.p(id: "en-S014")[#text("I shall not pursue this subject, however. Its bearing on the topic before us (namely, the mind-body problem) is that it enables us to make a general observation about the subjective character of experience. Whatever may be the status of facts about what it is like to be a human being, or a bat, or a Martian, these appear to be facts that embody a particular point of view.")]

#zh(id: "S014")[#text("不过，我不会继续追究这个主题。它与当前主题，也就是身心问题的关系，在于它允许我们对经验的主观特征作出一个一般观察。无论关于成为人、蝙蝠或火星人是什么感觉的事实具有何种地位，它们似乎都体现着一个特定视角。")]

#html.p(id: "en-S015")[#text("I am not adverting here to the alleged privacy of experience to its possessor. The point of view in question is not one accessible only to a single individual. Rather it is a type. It is often possible to take up a point of view other than one's own, so the comprehension of such facts is not limited to one's own case. There is a sense in which phenomenological facts are perfectly objective: one person can know or say of another what the quality of the other's experience is. They are subjective, however, in the sense that even this objective ascription of experience is possible only for someone sufficiently similar to the object of ascription to be able to adopt his point of view-to understand the ascription in the first person as well as in the third, so to speak. The more different from oneself the other experiencer is, the less success one can expect with this enterprise. In our own case we occupy the relevant point of view, but we will have as much difficulty understanding our own experience properly if we approach it from another point of view as we would if we tried to understand the experience of another species without taking up its point of view.8")]

#zh(id: "S015")[#text("我在这里并不是诉诸经验据说只对拥有者私有这一点。这里的视角并非只能由一个个体进入，而是一种类型。我们常能采取不同于自身的视角，所以对这些事实的理解，并不限于自己的情形。在某种意义上，现象学事实完全客观：一个人可以知道或说出另一个人的经验具有怎样的性质。但它们又是主观的，因为即便这种客观的经验归属，也只有足够类似于被归属者、能够采取其视角的人才做得到；可以说，他必须既以第三人称，也以第一人称理解这种归属。另一个经验者与自己差异越大，我们越不能期待成功。在自身情形中，我们占据相关视角；但如果改从另一个视角理解自己的经验，也会遇到与不采取其他物种视角而试图理解其经验同样的困难。⁸")]

#html.p(id: "en-S016")[#text("This bears directly on the mind-body problem. For if the facts of experience-facts about what it is like for the experiencing organism-are accessible only from one point of view, then it is a mystery how the true character of experiences could be revealed in the physical operation of that organism. The latter is a domain of objective facts par excellence-the kind that can be observed and understood from many points of view and by individuals with differing perceptual systems. There are no comparable imaginative obstacles to the acquisition of knowledge about bat neurophysiology by human scientists, and intelligent bats or Martians might learn more about the human brain than we ever will.")]

#zh(id: "S016")[#text("这直接关系到身心问题。因为，如果经验事实——关于经历经验的生物具有何种感觉的事实——只能从一个视角通达，那么这种生物的物理运作，究竟如何能够揭示经验的真实特征，就是一个谜。后者是最典型的客观事实领域，能够从许多视角，被拥有不同知觉系统的个体观察和理解。人类科学家获得蝙蝠神经生理知识，不会遇到类似的想象障碍；有智慧的蝙蝠或火星人，也可能比我们了解更多人脑知识。")]

#html.p(id: "en-S017")[#text("This is not by itself an argument against reduction. A Martian scientist with no understanding of visual perception could understand the rainbow, or lightning, or clouds as physical phenomena, though he would never be able to understand the human concepts of rainbow, lightning, or cloud, or the place these things occupy in our phenomenal world. The objective nature of the things picked out by these concepts could be apprehended by him because, although the concepts themselves are connected with a particular point of view and a particular visual phenomenology, the things apprehended from that point of view are not: they are observable from the point of view but external to it; hence they can be comprehended from other points of view also, either by the same organisms or by others. Lightning has an objective character that is not exhausted by its visual appearance, and this can be investigated by a Martian without vision. To be precise, it has a more objective character than is revealed in its visual appearance. In speaking of the move from subjective to objective characterization, I wish to remain noncommittal about the existence of an end point, the completely objective intrinsic nature of the thing, which one might or might not be able to reach. It may be more accurate to think of objectivity as a direction in which the understanding can travel. And in understanding a phenomenon like lightning, it is legitimate to go as far away as one can from a strictly human viewpoint.9")]

#zh(id: "S017")[#text("这本身并不是反对还原的论证。一个不理解视觉知觉的火星科学家，仍可以把彩虹、闪电或云理解为物理现象，尽管他永远无法理解人类的彩虹、闪电或云概念，也无法理解它们在人类现象世界中的位置。他能够把握这些概念所指事物的客观性质，因为虽然概念本身与特定视角、特定视觉现象学相联系，从该视角把握的事物却并非如此：它们可从该视角观察，却存在于它之外；所以，同一生物或其他生物，也可以从其他视角理解它们。闪电具有不被其视觉外观穷尽的客观特征，无视觉的火星人也能研究。准确说，它具有比视觉外观揭示的更客观的特征。谈论从主观刻画转向客观刻画时，我希望不对终点是否存在作出承诺，即不承诺事物完全客观的内在本性，是否是人可能到达的终点。把客观性视为理解可以前进的一个方向，也许更准确。在理解闪电等现象时，尽可能远离严格属于人类的视角，是正当的。⁹")]

#html.p(id: "en-S018")[#text("In the case of experience, on the other hand, the connection with a particular point of view seems much closer. It is difficult to understand what could be meant by the objective character of an experience, apart from the particular point of view from which its subject apprehends it. After all, what would be left of what it was like to be a bat if one removed the viewpoint of the bat? But if experience does not have, in addition to its subjective character, an objective nature that can be apprehended from many different points of view, then how can it be supposed that a Martian investigating my brain might be observing physical processes which were my mental processes (as he might observe physical processes which were bolts of lightning), only from a different point of view? How, for that matter, could a human physiologist observe them from another point of view?¹⁰")]

#zh(id: "S018")[#text("但经验与特定视角的联系，似乎紧密得多。离开经验主体把握经验的特定视角，经验的客观特征究竟意味着什么，很难理解。毕竟，如果去掉蝙蝠的视角，成为蝙蝠的感觉还剩什么？然而，如果经验除了主观特征，没有一种能够从许多不同视角把握的客观本性，那么怎能设想，研究我大脑的火星人，可能只是从另一视角，观察恰好就是我心理过程的物理过程，就像观察恰好就是闪电的物理过程那样？同样，一个人类生理学家又怎能从另一视角观察这些过程？¹⁰")]

#html.p(id: "en-S019")[#text("We appear to be faced with a general difficulty about psychophysical reduction. In other areas the process of reduction is a move in the direction of greater objectivity, toward a more accurate view of the real nature of things. This is accomplished by reducing our dependence on individual or species-specific points of view toward the object of investigation. We describe it not in terms of the impressions it makes on our senses, but in terms of its more general effects and of properties detectable by means other than the human senses. The less it depends on a specifically human viewpoint, the more objective is our description. It is possible to follow this path because although the concepts and ideas we employ in thinking about the external world are initially applied from a point of view that involves our perceptual apparatus, they are used by us to refer to things beyond themselves—toward which we have the phenomenal point of view. Therefore we can abandon it in favor of another, and still be thinking about the same things.")]

#zh(id: "S019")[#text("我们似乎面对着心理—物理还原的一种一般困难。在其他领域，还原是朝更大客观性前进，趋向对事物真实本性更准确的理解。这是通过减少研究时对个体或物种特定视角的依赖实现的。我们不以事物对感官造成的印象来描述它，而以其更一般的效果，以及能用人类感官之外的手段检测的性质来描述。描述越不依赖人类特有的视角，就越客观。之所以能够沿这条路走，是因为我们思考外界时使用的概念和思想，最初虽然从涉及自身知觉器官的视角应用，却被用来指向超出这些概念和思想本身的事物——我们对这些事物拥有现象视角。因此，我们可以放弃该视角，改用另一个，同时仍在思考相同的事物。")]

#html.p(id: "en-S020")[#text("Experience itself, however, does not seem to fit the pattern. The idea of moving from appearance to reality seems to make no sense here. What is the analogue in this case to pursuing a more objective understanding of the same phenomena by abandoning the initial subjective viewpoint toward them in favor of another that is more objective but concerns the same thing? Certainly it appears unlikely that we will get closer to the real nature of human experience by leaving behind the particularity of our human point of view and striving for a description in terms accessible to beings that could not imagine what it was like to be us. If the subjective character of experience is fully comprehensible only from one point of view, then any shift to greater objectivity -that is, less attachment to a specific viewpoint-does not take us nearer to the real nature of the phenomenon: it takes us farther away from it.")]

#zh(id: "S020")[#text("不过，经验本身似乎不符合这个模式。这里，从表象走向实在的想法，似乎没有意义。在这个案例中，放弃最初的主观视角，改用更客观、但仍针对同一事物的视角，以更客观地理解同一现象，其对应过程是什么？显然，如果我们抛下人类视角的特殊性，努力以那些无法想象成为我们是什么感觉的生物也能理解的术语来描述，就不大可能更接近人类经验的真实本性。如果经验的主观特征，只有从一个视角才能充分理解，那么任何向更大客观性的转变，也就是对特定视角更少依附，并不会使我们更接近现象的真实本性，反而使我们离它更远。")]

#html.p(id: "en-S021")[#text("In a sense, the seeds of this objection to the reducibility of experience are already detectable in successful cases of reduction; for in discovering sound to be, in reality, a wave phenomenon in air or other media, we leave behind one viewpoint to take up another, and the auditory, human or animal viewpoint that we leave behind remains unreduced. Members of radically different species may both understand the same physical events in objective terms, and this does not require that they understand the phenomenal forms in which those events appear to the senses of members of the other species. Thus it is a condition of their referring to a common reality that their more particular viewpoints are not part of the common reality that they both apprehend. The reduction can succeed only if the species-specific viewpoint is omitted from what is to be reduced.")]

#zh(id: "S021")[#text("在某种意义上，在成功还原的案例中，也已经能发现这种反对经验可还原性的论证的萌芽。因为，发现声音实际上是空气或其他介质中的波动现象时，我们放下一个视角，采用另一个；而被放下的人类或动物的听觉视角，仍然没有被还原。差异极大的物种成员，都可能用客观术语理解相同物理事件，而无须理解这些事件在另一物种感官中呈现的现象形式。因此，它们能够指向共同实在的一个条件，是各自更特殊的视角，不属于双方共同把握的实在。只有从还原对象中排除物种特有的视角，还原才能成功。")]

#html.p(id: "en-S022")[#text("But while we are right to leave this point of view aside in seeking a fuller understanding of the external world, we cannot ignore it permanently, since it is the essence of the internal world, and not merely a point of view on it. Most of the neobehaviorism of recent philosophical psychology results from the effort to substitute an objective concept of mind for the real thing, in order to have nothing left over which cannot be reduced. If we acknowledge that a physical theory of mind must account for the subjective character of experience, we must admit that no presently available conception gives us a clue how this could be done. The problem is unique. If mental processes are indeed physical processes, then there is something it is like, intrinsically,¹¹ to undergo certain physical processes. What it is for such a thing to be the case remains a mystery.")]

#zh(id: "S022")[#text("但在更全面地理解外界时，暂时放下这个视角虽是正确的，我们却不能永远忽略它，因为它是内在世界的本质，而不只是观察内在世界的一个视角。近期哲学心理学中的多数新行为主义，源于试图以客观的心灵概念替代真实心灵，使得没有任何无法还原的东西剩下。如果承认，心灵的物理理论必须解释经验的主观特征，就必须承认，目前没有任何可用概念，为如何实现这一点提供线索。这个问题是独特的。如果心理过程确实是物理过程，那么经历某些物理过程，本身就具有某种感觉。¹¹这样的事情究竟意味着什么，仍然是一个谜。")]

#html.p(id: "en-S023")[#text("What moral should be drawn from these reflections, and what should be done next? It would be a mistake to conclude that physicalism must be false. Nothing is proved by the inadequacy of physicalist hypotheses that assume a faulty objective analysis of mind. It would be truer to say that physicalism is a position we cannot understand because we do not at present have any conception of how it might be true. Perhaps it will be thought unreasonable to require such a conception as a condition of understanding. After all, it might be said, the meaning of physicalism is clear enough: mental states are states of the body; mental events are physical events. We do not know which physical states and events they are, but that should not prevent us from understanding the hypothesis. What could be clearer than the words \"is\" and \"are\"?")]

#zh(id: "S023")[#text("从这些反思应得出什么教训，接下来又该做什么？断定物理主义必定错误，将是一个错误。那些预设错误的客观心灵分析的物理主义假说不足以解释问题，并不能证明什么。更准确的说法是：物理主义是我们无法理解的立场，因为目前我们没有任何概念，能说明它何以可能为真。也许有人会认为，把这种概念作为理解的条件并不合理。毕竟，他们可能说，物理主义的意思已经足够清楚：心理状态是身体状态，心理事件是物理事件。我们不知道它们究竟是哪些物理状态与事件，但这不应妨碍理解假说。“是”这个词，还有什么比它更清楚？")]

#html.p(id: "en-S024")[#text("But I believe it is precisely this apparent clarity of the word \"is\" that is deceptive. Usually, when we are told that X is Y we know how it is supposed to be true, but that depends on a conceptual or theoretical background and is not conveyed by the \"is\" alone. We know how both \"X\" and \"Y\" refer, and the kinds of things to which they refer, and we have a rough idea how the two referential paths might converge on a single thing, be it an object, a person, a process, an event, or whatever. But when the two terms of the identification are very disparate it may not be so clear how it could be true. We may not have even a rough idea of how the two referential paths could converge, or what kind of things they might converge on, and a theoretical framework may have to be supplied to enable us to understand this. Without the framework, an air of mysticism surrounds the identification.")]

#zh(id: "S024")[#text("但我相信，恰恰是“是”这个词表面的清楚性，具有欺骗性。通常，别人告诉我们X是Y时，我们知道这句话何以应当为真，但这依赖概念或理论背景，并非单靠“是”字传达。我们知道“X”和“Y”如何指称、指称哪些类型的事物，也大致知道两条指称路径如何汇合于同一个事物，无论它是物体、人、过程、事件，还是其他东西。但当同一性陈述的两项差异极大时，它何以可能为真，就未必清楚了。我们甚至可能完全不知道，两条指称路径如何汇合，或汇合于什么类型的事物；必须提供一个理论框架，才能理解这一点。没有框架，同一性陈述就笼罩着神秘气氛。")]

#html.p(id: "en-S025")[#text("This explains the magical flavor of popular presentations of fundamental scientific discoveries, given out as propositions to which one must subscribe without really understanding them. For example, people are now told at an early age that all matter is really energy. But despite the fact that they know what \"is\" means, most of them never form a conception of what makes this claim true, because they lack the theoretical background.")]

#zh(id: "S025")[#text("这解释了为什么基础科学发现的通俗介绍常带有魔法意味：它们被宣布为一些必须接受、却未真正理解的命题。例如，如今人们很小就被告知，一切物质其实都是能量。但尽管知道“是”是什么意思，他们大多数人从未形成关于这个说法为何成立的理解，因为缺少理论背景。")]

#html.p(id: "en-S026")[#text("At the present time the status of physicalism is similar to that which the hypothesis that matter is energy would have had if uttered by a pre-Socratic philosopher. We do not have the beginnings of a conception of how it might be true. In order to understand the hypothesis that a mental event is a physical event, we require more than an understanding of the word \"is.\" The idea of how a mental and a physical term might refer to the same thing is lacking, and the usual analogies with theoretical identification in other fields fail to supply it. They fail because if we construe the reference of mental terms to physical events on the usual model, we either get a reappearance of separate subjective events as the effects through which mental reference to physical events is secured, or else we get a false account of how mental terms refer (for example, a causal behaviorist one).")]

#zh(id: "S026")[#text("目前，物理主义的地位，类似于一位前苏格拉底哲学家说出“物质是能量”这一假说时，它会具有的地位。我们甚至还没有开始构想，它何以可能为真。为了理解“心理事件是物理事件”这一假说，仅仅理解“是”字还不够。我们缺少关于心理术语与物理术语如何可能指向同一事物的观念，而与其他领域理论同一化所作的常见类比，并没有提供它。类比之所以失败，是因为按通常模式理解心理术语对物理事件的指称时，我们要么重新引入独立的主观事件，把它们视为心理术语得以指称物理事件的效果；要么得到关于心理术语如何指称的错误解释，例如因果行为主义的解释。")]

#html.p(id: "en-S027")[#text("Strangely enough, we may have evidence for the truth of something we cannot really understand. Suppose a caterpillar is locked in a sterile safe by someone unfamiliar with insect metamorphosis, and weeks later the safe is reopened, revealing a butterfly. If the person knows that the safe has been shut the whole time, he has reason to believe that the butterfly is or was once the caterpillar, without having any idea in what sense this might be so. (One possibility is that the caterpillar contained a tiny winged parasite that devoured it and grew into the butterfly.)")]

#zh(id: "S027")[#text("奇怪的是，我们可能拥有某件自己无法真正理解的事情为真的证据。假设，一个不熟悉昆虫变态的人，把毛毛虫锁进无菌保险箱；几周后重新打开，里面出现了一只蝴蝶。如果知道保险箱始终关闭，他就有理由相信，蝴蝶就是、或曾经就是那只毛毛虫，尽管完全不知道这种说法在何种意义上成立。一种可能性是，毛毛虫体内有一只小小的有翅寄生虫，它吃掉毛毛虫，再长成蝴蝶。")]

#html.p(id: "en-S028")[#text("It is conceivable that we are in such a position with regard to physicalism. Donald Davidson has argued that if mental events have physical causes and effects, they must have physical descriptions. He holds that we have reason to believe this even though we do not-and in fact could not-have a general psychophysical theory.12 His argument applies to intentional mental events, but I think we also have some reason to believe that sensations are physical processes, without being in a position to understand how. Davidson's position is that certain physical events have irreducibly mental properties, and perhaps some view describable in this way is correct. But nothing of which we can now form a conception corresponds to it; nor have we any idea what a theory would be like that enabled us to conceive of it.13")]

#zh(id: "S028")[#text("可以设想，我们面对物理主义时，也处于这样的境地。唐纳德·戴维森论证过，如果心理事件具有物理原因和结果，就必须具有物理描述。他认为，尽管我们没有、事实上也不可能拥有一种一般的心理—物理理论，仍有理由相信这一点。¹²他的论证适用于意向性心理事件，但我认为，我们也有某些理由相信，感觉是物理过程，尽管无法理解它们如何是物理过程。戴维森的立场是，某些物理事件具有不可还原的心理性质；也许某种可以这样描述的观点是正确的。但我们现在能形成概念的任何东西，都不与之对应；我们也不知道，能够使我们理解它的理论，会是什么样子。¹³")]

#html.p(id: "en-S029")[#text("Very little work has been done on the basic question (from which mention of the brain can be entirely omitted) whether any sense can be made of experiences' having an objective character at all. Does it make sense, in other words, to ask what my experiences are really like, as opposed to how they appear to me? We cannot genuinely understand the hypothesis that their nature is captured in a physical description unless we understand the more fundamental idea that they have an objective nature (or that objective processes can have a subjective nature).14")]

#zh(id: "S029")[#text("对于一个基本问题，人们做的工作很少，而这个问题完全可以不提大脑：说经验具有客观特征，究竟能否有任何意义？换言之，问“我的经验实际上是什么样子”，而不是“它们在我看来是什么样子”，有意义吗？除非理解更根本的观念，即经验具有客观本性，或者客观过程可以具有主观本性，否则我们不能真正理解“经验的本性可由物理描述把握”这一假说。¹⁴")]

#html.p(id: "en-S030")[#text("I should like to close with a speculative proposal. It may be possible to approach the gap between subjective and objective from another direction. Setting aside temporarily the relation between the mind and the brain, we can pursue a more objective understanding of the mental in its own right. At present we are completely unequipped to think about the subjective character of experience without relying on the imagination-without taking up the point of view of the experiential subject. This should be regarded as a challenge to form new concepts and devise a new method-an objective phenomenology not dependent on empathy or the imagination. Though presumably it would not capture everything, its goal would be to describe, at least in part, the subjective character of experiences in a form comprehensible to beings incapable of having those experiences.")]

#zh(id: "S030")[#text("最后，我想提出一个猜想。也许可以从另一个方向，接近主观与客观之间的鸿沟。暂时搁置心灵与大脑的关系，我们可以就心理本身，寻求一种更客观的理解。目前，如果不依赖想象、不采取经验主体的视角，我们就完全没有能力思考经验的主观特征。这应当被视为一项挑战：形成新概念，构想一种新方法——不依赖移情或想象的客观现象学。它大概无法捕捉一切，但目标是至少部分地描述经验的主观特征，并使那些无法拥有此类经验的生物，也能理解这种描述。")]

#html.p(id: "en-S031")[#text("We would have to develop such a phenomenology to describe the sonar experiences of bats; but it would also be possible to begin with humans. One might try, for example, to develop concepts that could be used to explain to a person blind from birth what it was like to see. One would reach a blank wall eventually, but it should be possible to devise a method of expressing in objective terms much more than we can at present, and with much greater precision. The loose intermodal analogies-for example, \"Red is like the sound of a trumpet\"-which crop up in discussions of this subject are of little use. That should be clear to anyone who has both heard a trumpet and seen red. But structural features of perception might be more accessible to objective description, even though something would be left out. And concepts alternative to those we learn in the first person may enable us to arrive at a kind of understanding even of our own experience which is denied us by the very ease of description and lack of distance that subjective concepts afford.")]

#zh(id: "S031")[#text("要描述蝙蝠的声呐经验，我们必须发展这样的现象学，但也可以从人类开始。例如，可以尝试发展一些概念，用来向生来失明的人解释，看见是什么感觉。最终会碰到无法逾越的墙，但应当能够构想一种方法，用客观术语表达比目前多得多的内容，而且精确得多。讨论这个主题时常出现的松散跨感官类比，例如“红色像小号的声音”，用处很小。听过小号、见过红色的人都应明白这一点。不过，知觉的结构特征，也许更容易得到客观描述，尽管仍会遗漏某些东西。采用不同于我们以第一人称学会的概念，还可能使我们对自身经验达到某种理解；而主观概念带来的描述便利和距离缺失，恰恰使这种理解难以获得。")]

#html.p(id: "en-S032")[#text("Apart from its own interest, a phenomenology that is in this sense objective may permit questions about the physical15 basis of experience to assume a more intelligible form. Aspects of subjective experience that admitted this kind of objective description might be better candidates for objective explanations of a more familiar sort. But whether or not this guess is correct, it seems unlikely that any physical theory of mind can be contemplated until more thought has been given to the general problem of subjective and objective. Otherwise we cannot even pose the mind-body problem without sidestepping it.16")]

#zh(id: "S032")[#text("除了本身的意义，这种意义上客观的现象学，也许能让关于经验物理¹⁵基础的问题，具有更可理解的形式。主观经验中容许这种客观描述的方面，也许更适于接受较熟悉类型的客观解释。但无论这一猜想是否正确，在对主观与客观的一般问题进行更多思考之前，似乎都难以设想任何心灵的物理理论。否则，我们连提出身心问题，都无法避免绕开它。¹⁶")]

== Notes / 注释

#html.p(id: "en-N001")[#text("1 Examples are J. J. C. Smart, Philosophy and Scientific Realism (London, 1963); David K. Lewis, \"An Argument for the Identity Theory,\" Journal of Philosophy, LXIII (1966), reprinted with addenda in David M. Rosenthal, Materialism & the Mind-Body Problem (Englewood Cliffs, N. J., 1971); Hilary Putnam, \"Psychological Predicates\" in Capitan and Merrill, Art, Mind, & Religion (Pittsburgh, 1967), reprinted in Rosenthal, op. cit., as \"The Nature of Mental States\"; D. M. Armstrong, A Materialist Theory of the Mind (London, 1968); D. C. Dennett, Content and Consciousness (London, 1969). I have expressed earlier doubts in \"Armstrong on the Mind,\" Philosophical Review, LXXIX (1970), 394-403; \"Brain Bisection and the Unity of Consciousness,\" Synthese, 22 (1971); and a review of Dennett, Journal of Philosophy, LXIX (1972). See also Saul Kripke, \"Naming and Necessity\" in Davidson and Harman, Semantics of Natural Language (Dordrecht, 1972), esp. pp. 334-342; and M. T. Thornton, \"Ostensive Terms and Materialism,\" The Monist, 56 (1972).")]

#zh(id: "N001")[#text("1. 例子包括：J. J. C. Smart，《哲学与科学实在论》（伦敦，1963）；David K. Lewis，《支持同一性理论的一个论证》，Journal of Philosophy，LXIII（1966），后附补充重印于David M. Rosenthal编《唯物主义与身心问题》（新泽西州恩格尔伍德克利夫斯，1971）；Hilary Putnam，《心理谓词》，收入Capitan与Merrill编《艺术、心灵与宗教》（匹兹堡，1967），并以《心理状态的本性》之名重印于Rosenthal前引书；D. M. Armstrong，《心灵的唯物主义理论》（伦敦，1968）；D. C. Dennett，《内容与意识》（伦敦，1969）。我此前在《Armstrong论心灵》，Philosophical Review，LXXIX（1970），394—403；《大脑分割与意识统一性》，Synthese，22（1971）；以及对Dennett的书评，Journal of Philosophy，LXIX（1972）中表达过怀疑。另见Saul Kripke，《命名与必然性》，收入Davidson与Harman编《自然语言的语义学》（多德雷赫特，1972），尤其334—342页；以及M. T. Thornton，《直示术语与唯物主义》，The Monist，56（1972）。")]

#html.p(id: "en-N002")[#text("2 Perhaps there could not actually be such robots. Perhaps anything complex enough to behave like a person would have experiences. But that, if true, is a fact which cannot be discovered merely by analyzing the concept of experience.")]

#zh(id: "N002")[#text("2. 也许这样的机器人实际上不可能存在。也许任何足够复杂、能够像人一样行动的东西，都有经验。但即便如此，这也不是仅靠分析经验概念就能发现的事实。")]

#html.p(id: "en-N003")[#text("3 It is not equivalent to that about which we are incorrigible, both because we are not incorrigible about experience and because experience is present in animals lacking language and thought, who have no beliefs at all about their experiences.")]

#zh(id: "N003")[#text("3. 它不等同于我们不可能判断错误的东西，因为我们对于经验并非绝不会出错，而且缺乏语言和思想的动物也有经验，尽管它们对自身经验没有任何信念。")]

#html.p(id: "en-N004")[#text("4 Cf. Richard Rorty, “Mind-Body Identity, Privacy, and Categories,” The Review of Metaphysics, XIX (1965), esp. 37–38.")]

#zh(id: "N004")[#text("4. 参见Richard Rorty，《身心同一性、私密性与范畴》，The Review of Metaphysics，XIX（1965），尤其37—38页。")]

#html.p(id: "en-N005")[#text("5 By \"our own case\" I do not mean just \"my own case,\" but rather the mentalistic ideas that we apply unproblematically to ourselves and other human beings.")]

#zh(id: "N005")[#text("5. “我们自身的情形”并不只指“我自身的情形”，而是指那些我们毫无困难地用于自己及其他人类的心理概念。")]

#html.p(id: "en-N006")[#text("6 Therefore the analogical form of the English expression “what it is like” is misleading. It does not mean “what (in our experience) it resembles,” but rather “how it is for the subject himself.”")]

#zh(id: "N006")[#text("6. 因此，英语表达“what it is like”的类比形式容易误导。它的意思并非“它类似于我们经验中的什么”，而是“对于主体自身，它是什么感觉”。")]

#html.p(id: "en-N007")[#text("7 Any intelligent extraterrestrial beings totally different from us.")]

#zh(id: "N007")[#text("7. 任何与我们完全不同、拥有智慧的外星生物。")]

#html.p(id: "en-N008")[#text("8 It may be easier than I suppose to transcend inter-species barriers with the aid of the imagination. For example, blind people are able to detect objects near them by a form of sonar, using vocal clicks or taps of a cane. Perhaps if one knew what that was like, one could by extension imagine roughly what it was like to possess the much more refined sonar of a bat. The distance between oneself and other persons and other species can fall anywhere on a continuum. Even for other persons the understanding of what it is like to be them is only partial, and when one moves to species very different from oneself, a lesser degree of partial understanding may still be available. The imagination is remarkably flexible. My point, however, is not that we cannot know what it is like to be a bat. I am not raising that epistemological problem. My point is rather that even to form a conception of what it is like to be a bat (and a fortiori to know what it is like to be a bat) one must take up the bat’s point of view. If one can take it up roughly, or partially, then one’s conception will also be rough or partial. Or so it seems in our present state of understanding.")]

#zh(id: "N008")[#text("8. 借助想象跨越物种间障碍，也许比我设想的容易。例如，盲人能够通过发出咂舌声或敲击手杖，运用某种声呐探测近处物体。如果知道那是什么感觉，也许就能进一步粗略想象，拥有蝙蝠更精细的声呐是什么感觉。自己与其他人、其他物种之间的距离，可以位于一个连续范围中的任何位置。即使对于其他人，理解成为他们是什么感觉，也只是部分的；面对与自己差异很大的物种时，仍可能获得程度更低的部分理解。想象具有惊人的灵活性。但我的要点不是说，我们不能知道成为蝙蝠是什么感觉。我并不是提出那个认识论问题。我的要点是，即便只要形成一个关于成为蝙蝠是什么感觉的概念，更不用说获得相关知识，也必须采取蝙蝠的视角。如果只能粗略或部分地采取它，那么概念也只能粗略或部分。至少，按照我们目前的理解，看起来如此。")]

#html.p(id: "en-N009")[#text("9 The problem I am going to raise can therefore be posed even if the distinction between more subjective and more objective descriptions or viewpoints can itself be made only within a larger human point of view. I do not accept this kind of conceptual relativism, but it need not be refuted to make the point that psychophysical reduction cannot be accommodated by the subjective-to-objective model familiar from other cases.")]

#zh(id: "N009")[#text("9. 因此，即使更主观与更客观的描述或视角之间的区分，本身只能在一个更广的人类视角内作出，我接下来提出的问题仍可以成立。我不接受这种概念相对主义，但无须反驳它，也能指出：心理—物理还原无法纳入其他案例中熟悉的从主观到客观的模式。")]

#html.p(id: "en-N010")[#text("10 The problem is not just that when I look at the \"Mona Lisa,\" my visual experience has a certain quality, no trace of which is to be found by someone looking into my brain. For even if he did observe there a tiny image of the \"Mona Lisa,\" he would have no reason to identify it with the experience.")]

#zh(id: "N010")[#text("10. 问题不只是：当我看《蒙娜丽莎》时，视觉经验具有某种性质，而查看我大脑的人找不到它的任何痕迹。因为即使他真的在脑内观察到一幅微小的《蒙娜丽莎》图像，也没有理由把它等同于经验。")]

#html.p(id: "en-N011")[#text("11 The relation would therefore not be a contingent one, like that of a cause and its distinct effect. It would be necessarily true that a certain physical state felt a certain way. Saul Kripke (op. cit.) argues that causal behaviorist and related analyses of the mental fail because they construe, e.g., \"pain\" as a merely contingent name of pains. The subjective character of an experience (\"its immediate phenomenological quality\" Kripke calls it [p. 340]) is the essential property left out by such analyses, and the one in virtue of which it is, necessarily, the experience it is. My view is closely related to his. Like Kripke, I find the hypothesis that a certain brain state should necessarily have a certain subjective character incomprehensible without further explanation. No such explanation emerges from theories which view the mind-brain relation as contingent, but perhaps there are other alternatives, not yet discovered. A theory that explained how the mind-brain relation was necessary would still leave us with Kripke's problem of explaining why it nevertheless appears contingent. That difficulty seems to me surmountable, in the following way. We may imagine something by representing it to ourselves either perceptually, sympathetically, or symbolically. I shall not try to say how symbolic imagination works, but part of what happens in the other two cases is this. To imagine something perceptually, we put ourselves in a conscious state resembling the state we would be in if we perceived it. To imagine something sympathetically, we put ourselves in a conscious state resembling the thing itself. (This method can be used only to imagine mental events and states-our own or another's.) When we try to imagine a mental state occurring without its associated brain state, we first sympathetically imagine the occurrence of the mental state: that is, we put ourselves into a state that resembles it mentally. At the same time, we attempt to perceptually imagine the non-occurrence of the associated physical state, by putting ourselves into another state unconnected with the first: one resembling that which we would be in if we perceived the nonoccurrence of the physical state. Where the imagination of physical features is perceptual and the imagination of mental features is sympathetic, it appears to us that we can imagine any experience occurring without its associated brain state, and vice versa. The relation between them will appear contingent even if it is necessary, because of the independence of the disparate types of imagination. (Solipsism, incidentally, results if one misinterprets sympathetic imagination as if it worked like perceptual imagination: it then seems impossible to imagine any experience that is not one's own.)")]

#zh(id: "N011")[#text("11. 因此，这种关系不会像原因与不同于它的结果之间的关系那样，是偶然的；某种物理状态具有某种感觉，将必然为真。Saul Kripke（前引书）论证，因果行为主义及相关心理分析之所以失败，是因为它们例如把“疼痛”解释为仅仅偶然地命名疼痛。经验的主观特征，Kripke称之为“其直接的现象学性质”（第340页），是这些分析遗漏的本质属性，经验也正因为这一属性，才必然是它所是的经验。我的观点与他很接近。像Kripke一样，如果没有进一步解释，我也无法理解“某种脑状态必定具有某种主观特征”这一假说。把身心关系视为偶然的理论，并没有提供这样的解释，但也许还有尚未发现的其他选择。即使某个理论解释了身心关系为何必然，仍会留下Kripke的问题：为什么它看起来是偶然的？我认为，可以这样克服困难。我们可以通过知觉性的、移情性的或符号性的自我表征，来想象某件事物。我不打算解释符号想象的运作，但其他两种情形的部分过程如下。知觉性地想象某物，是让自己处于类似于感知该物时会有的意识状态；移情性地想象某物，则是让自己处于类似于该物本身的意识状态。这后一方法，只能用于想象自己或他人的心理事件与状态。试图想象心理状态出现、相应脑状态却不出现时，我们先移情地想象心理状态的发生，也就是进入一个心理上类似的状态。同时，尝试知觉性地想象相应物理状态不发生，使自己进入另一个与前者无关的状态，类似于感知物理状态不发生时会有的状态。当对物理特征的想象属于知觉性的，对心理特征的想象属于移情性的，我们便觉得，能够想象任何经验在没有相应脑状态时发生，反之亦然。即使关系是必然的，它仍会显得偶然，因为两种不同想象类型彼此独立。顺便说，如果把移情性想象误解为像知觉性想象那样工作，就会产生唯我论：这时，想象任何不属于自己的经验，都似乎不可能。")]

#html.p(id: "en-N012")[#text("12 See “Mental Events” in Foster and Swanson, Experience and Theory (Amherst, 1970); though I don’t understand the argument against psychophysical laws.")]

#zh(id: "N012")[#text("12. 见Foster与Swanson编《经验与理论》（阿默斯特，1970）中的《心理事件》；不过，我不理解其中反对心理—物理规律的论证。")]

#html.p(id: "en-N013")[#text("13 Similar remarks apply to my paper “Physicalism,” Philosophical Review LXXIV (1965), 339–356, reprinted with postscript in John O’Connor, Modern Materialism (New York, 1969).")]

#zh(id: "N013")[#text("13. 类似评论也适用于我的《物理主义》，Philosophical Review，LXXIV（1965），339—356；后附后记重印于John O’Connor编《现代唯物主义》（纽约，1969）。")]

#html.p(id: "en-N014")[#text("14 This question also lies at the heart of the problem of other minds, whose close connection with the mind-body problem is often overlooked. If one understood how subjective experience could have an objective nature, one would understand the existence of subjects other than oneself.")]

#zh(id: "N014")[#text("14. 这个问题也处在他心问题的核心，后者与身心问题的密切联系常被忽略。如果理解主观经验如何具有客观本性，就会理解自身之外的主体如何存在。")]

#html.p(id: "en-N015")[#text("15 I have not defined the term “physical.” Obviously it does not apply just to what can be described by the concepts of contemporary physics, since we expect further developments. Some may think there is nothing to prevent mental phenomena from eventually being recognized as physical in their own right. But whatever else may be said of the physical, it has to be objective. So if our idea of the physical ever expands to include mental phenomena, it will have to assign them an objective character—whether or not this is done by analyzing them in terms of other phenomena already regarded as physical. It seems to me more likely, however, that mental-physical relations will eventually be expressed in a theory whose fundamental terms cannot be placed clearly in either category.")]

#zh(id: "N015")[#text("15. 我没有定义“物理”一词。显然，它不只适用于当代物理学概念能描述的东西，因为我们期待进一步发展。有些人可能认为，没有什么能阻止心理现象最终凭自身被承认为物理现象。但无论对物理还能说什么，它都必须是客观的。因此，如果物理概念扩展到包含心理现象，就必须赋予它们客观特征，无论是否通过把它们分析为其他已被视为物理的现象来实现。不过，我认为更可能的是，心理—物理关系最终将以一种理论表达，其中基本术语无法明确归入任何一类。")]

#html.p(id: "en-N016")[#text("16 I have read versions of this paper to a number of audiences, and am indebted to many people for their comments.")]

#zh(id: "N016")[#text("16. 我曾向多批听众宣读本文的不同版本，许多人提出评论，在此致谢。")]
